#Gradle
org.gradle.jvmargs=-Xmx6144M -XX:MaxMetaspaceSize=1024M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M -XX:MaxMetaspaceSize=768M"
org.gradle.caching=true
org.gradle.configuration-cache=true
#Kotlin
kotlin.code.style=official
kotlin.js.compiler=ir
#MPP
kotlin.mpp.enableCInteropCommonization=true
#Compose Experimental targets
org.jetbrains.compose.experimental.jscanvas.enabled=true
org.jetbrains.compose.experimental.macos.enabled=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
#Publishing
paycraft.version=2.3.2
SONATYPE_HOST=CENTRAL_PORTAL
SONATYPE_AUTOMATIC_RELEASE=true

